name: build
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: onichandame/nats-action@master
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - run: go get .
      - run: go build
      - run: go test -json > test-results.json
      - uses: actions/upload-artifact@v4
        with: 
          path: test-results.json
